[package]
name = "ip_license_agreement"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.1"
openzeppelin = "0.20.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.34.0" }
assert_macros = "2.8.5"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
